on:
  [push]
#  release:
#    types: [published]

name: Release

jobs:
  build:
    name: Java SDK Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          server-id: splunk-artifactory
      - name: build
        run: mvn package --file pom.xml -DskipTests=true
#      - name: Create GitHub Release
#        uses: softprops/action-gh-release@v1
#        with:
##          body_path: ${{ github.workflow }}-CHANGELOG.txt
#          files: ./target/*.jarln -s /data/to/zip/data.txt data.txt
#          draft: true
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Deploy to Artifactory
#        run: mvn --batch-mode deploy -DskipTests=true
#        env:
#          MAVEN_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
#          MAVEN_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
#
#      - name: Zip docs
#        run: |
#          cd splunk/target/apidocs
#          zip -r ./../../../apidocs/docs.zip ./*
#          cd ../../..

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: java_sdk_docs
          path: splunk/target/apidocs
